version: '3.7'

services:
  db:
    container_name: "mysql-db"
    build:
      context: "./docker/mysql"
      dockerfile: Dockerfile
    networks:
      - default
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'todo_app'
      MYSQL_USER: 'tester'
      MYSQL_PASSWORD: 'pass'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  api:
    container_name: "todo-app"
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "40000:40000"  # port mapping for Delve debugging
    depends_on:
      - db
    volumes:
      - .:/app/
    networks:
      - default
networks:
  default:
volumes:
  mysql_data: